carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"
urlpatterns = [
    path('carts/promocode/', views.PromoCodeView.as_view(), name='promo-view'),
    path('carts/<int:pk>/', views.CartView.as_view(), name='cart-view'),
    path('carts/', views.CartView.as_view(), name='list-cart-view'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView
from azbankgateways.urls import az_bank_gateways_urls

admin.site.site_header = 'پنل مدیریت تهران بوتیک'
admin.site.index_title = 'پنل مدیریت فروشگاه'
admin.site.site_title = 'صفحه مدیریت تهران بوتیک'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('medias.urls', namespace="medias")),
    path('', include('products.urls', namespace="products")),
    path('', include('addresses.urls', namespace="addresses")),
    path('', include('carts.urls', namespace="carts")),
    path('', include('orders.urls', namespace="orders")),
    path("bankgateways/", az_bank_gateways_urls()),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path('orders/', views.CreateOrderView.as_view(), name="create-order"),
    path('orders/list/pdf/', views.GenerateOrderPDF.as_view(), name='orders-list-pdf'),
    path('checkout/', views.CheckoutView.as_view(), name="checkout-view"),
    path('callback/', views.callback, name="callback-view")
]

carts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from accounts.models import User
from carts.managers import CartItemManager
from core.models import AbstractBaseModel
from products import DiscountType
from products.models import ProductVariant
from django.utils import timezone


class PromoCode(AbstractBaseModel):
    code = models.CharField(_("Promo Code"), max_length=255)
    code_type = models.CharField(
        _("Code Type"),
        max_length=25,
        choices=DiscountType.choices
    )
    value = models.IntegerField(_("Value"))
    expiration_date = models.DateTimeField(_("Expiration Date"))
    active = models.BooleanField(_("Active"), default=False)

    class Meta:
        verbose_name = _("Promo Code")
        verbose_name_plural = _("Promo Codes")

    def apply_discount(self, original_price):
        if self.code_type == DiscountType.CONSTANT:
            return max(0, original_price - self.value)
        elif self.code_type == DiscountType.PERCENTAGE:
            return max(0, original_price * (1 - (self.value / 100)))
        return original_price

    def is_valid(self):
        if self.active and self.expiration_date >= timezone.now():
            return True
        return False

    def __str__(self):
        return self.code


class CartItem(AbstractBaseModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="cartitems",
        verbose_name=_("User")
    )
    product_variant = models.ForeignKey(
        ProductVariant,
        on_delete=models.CASCADE,
        verbose_name=_("Product Variant")
    )
    quantity = models.PositiveIntegerField(_("Quantity"))
    deleted_or_paid = models.BooleanField(_("Deleted or paid"), default=False)

    objects = CartItemManager()

    class Meta:
        verbose_name = _("Cart Item")
        verbose_name_plural = _("Cart Items")

    def get_price(self):
        return self.quantity * self.product_variant.price

    def get_discount(self):
        discount = 0
        if self.product_variant.product.is_discounted():
            if self.product_variant.product.discount_type == DiscountType.CONSTANT:
                discount = self.product_variant.product.discount_value
            elif self.product_variant.product.discount_type == DiscountType.PERCENTAGE:
                discount = (self.product_variant.price * self.product_variant.product.discount_value) / 100
        return discount

    def __str__(self):
        return self.user.phone_number

carts/forms.py
from django import forms
from carts.models import PromoCode
from django.core.exceptions import ValidationError


class PromoCodeForm(forms.ModelForm):
    class Meta:
        model = PromoCode
        fields = ('code',)

    def clean_code(self):
        code = self.cleaned_data.get('code')
        queryset = PromoCode.objects.filter(code__exact=code)
        if queryset.exists():
            instance = queryset.first()
            if instance.is_valid():
                return code
            raise ValidationError('کد تخفیف شما معتبر نمی باشد.')
        raise ValidationError('کد تخفیف شما معتبر نمی باشد.')

carts/views.py
from django.contrib import messages
from django.http import QueryDict
from django.shortcuts import render, get_object_or_404
from carts.forms import PromoCodeForm
from carts.models import CartItem, PromoCode
from core.views import ProtectedView
from products.models import ProductVariant


# Create your views here.
class BaseCartView(ProtectedView):
    template_name = "carts/basket.html"

    def get_context(self):
        queryset = CartItem.objects.select_related(
            "product_variant",
            "product_variant__variant_image",
            "product_variant__product"
        ).filter(user=self.request.user, deleted_or_paid=False)

        total_price = sum([x.get_price() for x in queryset])
        total_discount = sum([x.get_discount() for x in queryset])

        return {
            'total_price': f"{format(total_price, ',')} تومان",
            'total_discount': f"{format(int(total_discount), ',')} تومان",
            'purchase_price': f"{format(int(total_price - total_discount), ',')} تومان",
            'purchase_price_int': int(total_price - total_discount),
            'promo_code_discount': '0 تومان',
            'shipping_cost': f"0 تومان",
            'promo_code_form': PromoCodeForm(),
            'cartitems': queryset
        }

    def render_html(self, section=""):
        context = self.get_context()
        return render(self.request, template_name=self.template_name + section, context=context)


class CartView(BaseCartView):
    variant = None
    body = None

    def setup(self, request, *args, **kwargs):
        if request.method != 'GET':
            self.variant = get_object_or_404(ProductVariant, pk=kwargs.get('pk'))
        self.body = QueryDict(request.body)

        super().setup(request, *args, **kwargs)

    def is_valid_stock(self, stock):
        if stock is None or not stock.isdigit():
            messages.warning(self.request, message='تعداد محصول انتخاب نشده است.')
            return False
        elif int(stock) > self.variant.stock:
            messages.warning(self.request,
                             message=f'"{self.variant.product.name + " - " + ", ".join([x.name for x in self.variant.variables.all()])}" با این تعداد در انبار موجود نیست.')
            return False
        return True

    def is_valid_variant(self):
        if self.variant is None:
            messages.error(self.request, message='این محصول موجود نیست.')
            return False
        return True

    def update_or_create(self, stock):
        return CartItem.objects.update_or_create(
            user=self.request.user,
            product_variant=self.variant,
            quantity=stock,
        )

    def post(self, request, pk):
        stock = self.body.get('stock')

        if not self.is_valid_stock(stock):
            return render(request, template_name="partials/alert.html")

        if not self.is_valid_variant():
            return render(request, template_name="partials/alert.html")

        self.update_or_create(stock)

        message = f'{self.variant.product.name} با موفقیت به سبد خرید اضافه شد.'
        messages.success(request, message=f'{self.variant.product.name} با موفقیت به سبد خرید اضافه شد.')
        return render(request, template_name="partials/alert.html", context={'type': 'success', 'message': message})

    def patch(self, request, pk):
        cart = CartItem.objects.get(user=request.user, product_variant=self.variant, deleted_or_paid=False)

        if self.body.get("type") == "increase":
            stock = cart.quantity + 1

            if not self.is_valid_stock(str(stock)):
                return self.render_html("#basket")

            if not self.is_valid_variant():
                return self.render_html("#basket")
        else:
            if cart.quantity == 1:
                cart.delete()
                return self.render_html("#basket")
            else:
                stock = cart.quantity - 1

        self.update_or_create(stock)

        return self.render_html("#basket")

    def delete(self, request, pk):
        cart = CartItem.objects.get(user=request.user, product_variant=self.variant)
        cart.deleted_or_paid = True
        cart.save()
        return self.render_html("#basket")

    def get(self, request):
        return self.render_html()


class PromoCodeView(BaseCartView):
    promo_code = None

    def get_context(self):
        context = super(PromoCodeView, self).get_context()

        if self.promo_code:
            purchase_price = context.get('purchase_price_int', 0)

            discount_price = self.promo_code.apply_discount(purchase_price)
            discount_amount = purchase_price - discount_price

            context['promo_code_discount'] = f"{format(int(discount_amount), ',')} تومان"
            context['purchase_price'] = f"{format(int(discount_price), ',')} تومان"
            context['promo_code_form'] = PromoCodeForm(initial={'code': self.promo_code.code})
        return context

    def post(self, request):
        form = PromoCodeForm(request.POST)

        if form.is_valid():
            code = form.cleaned_data.get('code')
            try:
                self.promo_code = PromoCode.objects.get(code__iexact=code, active=True)

                if not self.promo_code.is_valid():
                    messages.error(request, 'کد تخفیف شما منقضی شده است.')
                    return self.render_html("#basket")

                messages.success(request, 'کد تخفیف با موفقیت ثبت شد.')
                return self.render_html("#basket")

            except PromoCode.DoesNotExist:
                messages.error(request, 'کد تخفیف شما معتبر نمی‌باشد.')
                return self.render_html("#basket")

        messages.error(request, 'کد تخفیف شما معتبر نمی‌باشد.')
        return self.render_html("#basket")

carts/templates/carts/basket.html
{% extends 'base.html' %}
{% load static %}
{% load partials %}
{% load widget_tweaks %}

{% block title %}
    سبد خرید
{% endblock %}

{% block content %}
    {% partialdef basket inline %}
        <div class="container px-4" id="basket">
            <div class="justify-center my-8 hidden lg:flex">
                <ul class="steps steps-vertical lg:steps-horizontal">
                    <li class="step text-sm step-primary font-bold">سبد خرید</li>
                    <li class="step text-sm font-bold">اطلاعات آدرس</li>
                    <li class="step text-sm font-bold">پرداخت</li>
                </ul>
            </div>

            <div class="lg:grid grid-cols-12 gap-10">
                <div class="col-span-12 lg:col-span-8">
                    <div id="messages" class="mt-4 lg:mt-0">{% include 'partials/alert.html' %}</div>
                    <h4 class="border-b py-2 font-bold">سبد خرید</h4>
                    {% for cartitem in cartitems %}
                        <!-- desktop -->
                        <div class="items-center justify-between border-b py-4 hidden lg:flex">
                            <div>
                                <button hx-delete="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                        hx-target="#basket" hx-swap="outerHTML">
                                    <img src="{% static 'images/icons/CloseSquare-Linear-32px.svg' %}" alt="remove">
                                </button>
                            </div>
                            <div>
                                <img src="{{ cartitem.product_variant.variant_image.image.url }}" class="rounded-lg"
                                     width="200" height="200"
                                     alt="{{ cartitem.product_variant.variant_image.alt_text }}">
                            </div>
                            <div>
                                <h1 class="font-bold">{{ cartitem.product_variant.product.name }}
                                    - {{ cartitem.product_variant.variables.all|join:' ,' }}</h1>
                            </div>
                            <div>
                                <p class="font-bold text-sm">{{ cartitem.product_variant.product.get_price_text }}</p>
                            </div>
                            <div class="flex relative">
                                <button type="button" hx-patch="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                        hx-target="#basket" hx-swap="outerHTML" hx-vals='{"type": "increase"}'
                                        class="btn btn-outline btn-xs input-bordered absolute bg-white right-0">+
                                </button>
                                <input
                                        disabled
                                        name="stock"
                                        type="text"
                                        placeholder="تعداد"
                                        value="{{ cartitem.quantity }}"
                                        class="input input-bordered input-xs w-24 px-8 text-center"/>
                                <button {% if cartitem.quantity <= 1 %}disabled{% endif %} type="button"
                                        hx-patch="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                        hx-target="#basket" hx-swap="outerHTML" hx-vals='{"type": "decrease"}'
                                        class="btn btn-outline input-bordered btn-xs absolute bg-white left-0">-
                                </button>
                            </div>
                        </div>
                        <!-- mobile -->
                        <div class="items-center justify-between border-b py-4 flex lg:hidden {% if forloop.last %}mb-4{% endif %}">
                            <div class="flex gap-4 w-full justify-between">
                                <div class="flex gap-4">
                                    <img src="{{ cartitem.product_variant.variant_image.image.url }}" class="rounded-lg"
                                         width="150" height="150"
                                         alt="{{ cartitem.product_variant.variant_image.alt_text }}">
                                    <div class="flex flex-col justify-around text-xs font-bold">
                                        <p>{{ cartitem.product_variant.product.name }}
                                            - {{ cartitem.product_variant.variables.all|join:' ,' }}</p>
                                        <p>تعداد</p>
                                        <p>قیمت</p>
                                    </div>
                                </div>

                                <div class="flex flex-col justify-around text-sm font-bold items-end">
                                    <button hx-delete="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                            hx-target="#basket" hx-swap="outerHTML">
                                        <img src="{% static 'images/icons/CloseSquare-Linear-32px.svg' %}" alt="remove">
                                    </button>
                                    <div class="flex relative">
                                        <button type="button"
                                                hx-patch="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                                hx-target="#basket" hx-swap="outerHTML" hx-vals='{"type": "increase"}'
                                                class="btn btn-outline btn-xs input-bordered absolute bg-white right-0">
                                            +
                                        </button>
                                        <input
                                                disabled
                                                name="stock"
                                                type="text"
                                                placeholder="تعداد"
                                                value="{{ cartitem.quantity }}"
                                                class="input input-bordered input-xs w-24 px-8 text-center"/>
                                        <button {% if cartitem.quantity <= 1 %}disabled{% endif %} type="button"
                                                hx-patch="{% url 'carts:cart-view' cartitem.product_variant.id %}"
                                                hx-target="#basket" hx-swap="outerHTML" hx-vals='{"type": "decrease"}'
                                                class="btn btn-outline input-bordered btn-xs absolute bg-white left-0">-
                                        </button>
                                    </div>
                                    <p>{{ cartitem.product_variant.product.get_price_text }}</p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-span-12 lg:col-span-4 flex flex-col gap-4">
                    <div class="border rounded-lg p-4">
                        <div class="border-b pb-4 mb-4">
                            <h4 class="font-bold text-sm">کد تخفیف</h4>
                            <p class="text-xs my-3">کد تخفیف کد معرف کارت هدیه خود را در زیر وارد کرده و دکمه ثبت رو
                                بزنید تا در صورت داشتن اعتبار به سفارش شما اعمال شود.</p>
                            <form novalidate class="flex gap-4" hx-post="{% url 'carts:promo-view' %}"
                                  hx-target="#basket" hx-swap="outerHTML">
                                {% render_field promo_code_form.code class="input input-bordered w-full" %}
                                <button type="submit" class="btn btn-outline btn-primary">ثبت</button>
                            </form>
                        </div>

                        <div class="flex flex-col gap-4 border-b pb-4 mb-4">
                            <div class="flex justify-between text-xs font-bold">
                                <p>قیمت کالا ها</p>
                                <p>{{ total_price }}</p>
                            </div>

                            <div class="flex justify-between text-xs font-bold items-center">
                                <p class="flex flex-row-reverse gap-2 items-center">مجموع تخفیف روی کالا ها <img
                                        src="{% static 'images/icons/ReceiptDiscount-Linear-32px.svg' %}"
                                        alt="discount"></p>
                                <p class="text-error">{{ promo_code_discount }}</p>
                            </div>

                            <div class="flex justify-between text-xs font-bold">
                                <p>سود شما از خرید</p>
                                <p>{{ total_discount }}</p>
                            </div>

                            <div class="flex justify-between text-xs font-bold">
                                <p>هزینه ارسال</p>
                                <p>{{ shipping_cost }}</p>
                            </div>
                        </div>

                        <div class="">
                            <div class="flex justify-between text-base font-bold">
                                <p>جمع مبلغ پرداخت</p>
                                <p>{{ purchase_price }}</p>
                            </div>
                            <form hx-post="{% url 'orders:create-order' %}" hx-swap="innerHTML" hx-target="#messages">
                                {% render_field promo_code_form.code type="hidden" class="input input-bordered w-full" %}
                                <button class="btn mt-4 btn-primary w-full">
                                    ثبت سفارش
                                </button>
                            </form>
                        </div>
                    </div>

                    <div class="border rounded-lg p-4 mb-5">
                        <ul class="list-disc text-sm p-4 leading-8">
                            <li>در صورت اتمام موجودی‌، کالاها از سبد خرید حذف میشوند.</li>
                            <li>لطفا در طول مراحل خرید فیلتر شکن خود را خاموش کنید.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    {% endpartialdef %}
{% endblock %}