accounts/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView
from accounts.api import views as api_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='user-login-view'),
    path('login/verify/', views.VerifyLogin.as_view(), name='user-login-verify-view'),
    path('logout/', views.logout_view, name='user-logout-view'),

    path('profile/account-detail/', views.ProfileDetailView.as_view(), name="user-profile-detail"),
    path('profile/orders-detail/', views.ProfileOrdersView.as_view(), name="user-profile-orders"),

    path('signup/', views.SignupView.as_view(), name="user-signup-view"),
    path('signup/verify/', views.VerifySignup.as_view(), name='user-signup-verify-view'),

    path('api/users/', api_views.UserListView.as_view(), name='user-list-api'),
    path('api/users/<int:pk>/', api_views.UserRetrieveView.as_view(), name='user-retrieve-api'),
    path('api/users/delete/<int:pk>/', api_views.UserDeleteView.as_view(), name='user-delete-api'),
    path('api/users/update/<int:pk>/', api_views.UserUpdateView.as_view(), name='user-update-api'),
    path('api/users/update/', api_views.UserEditView.as_view(), name='user-update-profile-api'),
    path('api/register/', api_views.UserRegisterView.as_view(), name='user-register-api'),
    path('api/login/', TokenObtainPairView.as_view(), name='user-login-api'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView
from azbankgateways.urls import az_bank_gateways_urls

admin.site.site_header = 'پنل مدیریت تهران بوتیک'
admin.site.index_title = 'پنل مدیریت فروشگاه'
admin.site.site_title = 'صفحه مدیریت تهران بوتیک'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('medias.urls', namespace="medias")),
    path('', include('products.urls', namespace="products")),
    path('', include('addresses.urls', namespace="addresses")),
    path('', include('carts.urls', namespace="carts")),
    path('', include('orders.urls', namespace="orders")),
    path("bankgateways/", az_bank_gateways_urls()),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from accounts.managers import UserManager
from django.utils import timezone


class User(AbstractBaseUser):
    first_name = models.CharField(_("First Name"), max_length=50)
    last_name = models.CharField(_("Last Name"), max_length=50)
    phone_number = models.CharField(
        _("Phone Number"),
        max_length=11,
        unique=True,
        validators=[
            RegexValidator(
                regex=r'^09(0[0-5]|[1 3]\d|2[0-3]|9[0-9]|41)\d{7}$',
                message=_("Enter a valid phone number."),
                code="invalid_phone"
            )
        ]
    )
    is_active = models.BooleanField(_("Is Active"), default=False)
    is_admin = models.BooleanField(_("Is Admin"), default=False)

    otp = models.CharField(_("One-Time Password (OTP)"), max_length=5, null=True, blank=True)
    otp_expiry = models.DateTimeField(_("OTP Expiry"), blank=True, null=True)

    objects = UserManager()

    USERNAME_FIELD = "phone_number"
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def otp_is_expired(self):
        if self.otp_expiry and self.otp_expiry < timezone.now():
            return True
        return False

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    @property
    def is_staff(self):
        return self.is_admin

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from accounts.models import User
import re


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label=_('password'), widget=forms.PasswordInput)
    confirm_password = forms.CharField(label=_('confirm password'), widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['phone_number', 'first_name', 'last_name']

    def clean_confirm_password(self):
        # Check that the two password entries match
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and confirm_password and password != confirm_password:
            raise ValidationError(_("Passwords don't match"))
        return confirm_password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['confirm_password'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ['phone_number', 'first_name', 'last_name', 'is_active', 'is_admin']


class LoginForm(forms.Form):
    phone_number = forms.CharField(max_length=11, min_length=11)

    def clean_phone_number(self):
        cd = super().clean()
        phone_number = cd.get('phone_number')

        if not re.match(
                '^09((14)|(13)|(12)|(19)|(18)|(17)|(15)|(16)|(11)|(10)|(90)|(91)|(92)|(93)|(94)|(95)|(96)|(32)|(30)|(33)|(35)|(36)|(37)|(38)|(39)|(00)|(01)|(02)|(03)|(04)|(05)|(41)|(20)|(21)|(22)|(23)|(31)|(34)|(9910)|(9911)|(9913)|(9914)|(9999)|(999)|(990)|(9810)|(9811)|(9812)|(9813)|(9814)|(9815)|(9816)|(9817)|(998))\d{7}$', phone_number):
            raise ValidationError('شماره تلفن همراه نا معتبر است.')
        return phone_number


class VerifyOtpFrom(forms.Form):
    phone_number = forms.CharField(max_length=11, min_length=11)
    otp = forms.CharField(max_length=5, min_length=5)

    def clean_otp(self):
        cd = super().clean()
        users = User.objects.filter(phone_number=cd.get('phone_number'), otp=cd.get('otp'))
        if not users.exists() or users.first().otp_is_expired():
            raise ValidationError('کد تایید صحیح نمی باشد لطفا دوباره تلاش کنید.')


class SignupForm(forms.Form):
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)
    password = forms.CharField(widget=forms.PasswordInput, min_length=8, max_length=16)
    phone_number = forms.CharField(max_length=11, min_length=11)

    def clean_phone_number(self):
        cd = super().clean()
        phone_number = cd.get('phone_number')

        if not re.match(
                '^09((14)|(13)|(12)|(19)|(18)|(17)|(15)|(16)|(11)|(10)|(90)|(91)|(92)|(93)|(94)|(95)|(96)|(32)|(30)|(33)|(35)|(36)|(37)|(38)|(39)|(00)|(01)|(02)|(03)|(04)|(05)|(41)|(20)|(21)|(22)|(23)|(31)|(34)|(9910)|(9911)|(9913)|(9914)|(9999)|(999)|(990)|(9810)|(9811)|(9812)|(9813)|(9814)|(9815)|(9816)|(9817)|(998))\d{7}$',
                phone_number):
            raise ValidationError('شماره تلفن همراه نا معتبر است.')

        user = User.objects.filter(phone_number=phone_number, is_active=True).first()
        if user:
            raise ValidationError('کاربری با این مشخصات قبلا ثبت نام کرده است.')

        return phone_number


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)

accounts/api/views.py
from accounts.api.serializers import UserSerializer, UserCreateUpdateSerializer
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from accounts.api.mixins import UserPasswordUpdateMixin
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    CreateAPIView,
    DestroyAPIView,
    UpdateAPIView
)
from accounts.models import User


# admin panel user list
class UserListView(ListAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser, )


# admin panel retrieve user
class UserRetrieveView(RetrieveAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser, )
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


# admin panel delete user
class UserDeleteView(DestroyAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser, )
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


# admin panel update user
class UserUpdateView(UserPasswordUpdateMixin, UpdateAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser, )
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class UserRegisterView(CreateAPIView):
    serializer_class = UserCreateUpdateSerializer
    queryset = User.objects.all()
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAuthenticated, )

    def perform_create(self, serializer):
        validated_data = serializer.validated_data
        User.objects.create_user(
            phone_number=validated_data.get('phone_number'),
            first_name=validated_data.get('first_name'),
            last_name=validated_data.get('last_name'),
            password=validated_data.get('password')
        )


class UserEditView(UserPasswordUpdateMixin, UpdateAPIView):
    serializer_class = UserCreateUpdateSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAuthenticated, )

    def get_object(self):
        return User.objects.get(pk=self.request.user.id)

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django_htmx.http import HttpResponseClientRedirect
from django.views.generic import View
from accounts.forms import LoginForm, VerifyOtpFrom, SignupForm, UserProfileUpdateForm
from accounts.models import User
from random import randint
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.shortcuts import redirect
from accounts.tasks import send_otp
from orders import OrderStatus
from orders.models import Order
from django.urls import reverse


class LoginView(View):
    template_name = "accounts/login.html"
    confirm_template_name = "accounts/login-otp-form.html"

    form_class = LoginForm
    confirm_form_class = VerifyOtpFrom

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.htmx:
                return HttpResponseClientRedirect(reverse('home'))
            return redirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {
            'form': self.form_class()
        }
        return render(request, template_name=self.template_name, context=context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            users = User.objects.filter(phone_number=form.cleaned_data.get("phone_number"))
            if users.exists():
                otp = randint(10000, 99999)
                user = users.first()
                user.otp = otp
                user.otp_expiry = timezone.now() + timedelta(seconds=settings.EXPIRE_OTP)
                user.save()
                send_otp.apply_async((form.cleaned_data.get("phone_number"), otp), )
            context = {
                'form': self.confirm_form_class(initial={'phone_number': form.cleaned_data.get("phone_number")}),
            }
            return render(request, template_name=self.confirm_template_name, context=context)
        return render(request, template_name=f"{self.template_name}#login_form", context={'form': form})


class VerifyLogin(View):
    form_class = VerifyOtpFrom
    template_name = "accounts/login-otp-form.html"
    success_url = reverse_lazy('home')

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.get(phone_number=cd.get('phone_number'))
            login(request=request, user=user)
            user.otp = None
            user.otp_expiry = None
            user.save()
            return HttpResponseClientRedirect(redirect_to=self.success_url)
        return render(request, template_name=f"{self.template_name}#verify_otp_form", context={'form': form})


class SignupView(View):
    template_name = "accounts/signup.html"
    confirm_template_name = "accounts/signup-otp-form.html"
    form_class = SignupForm
    confirm_form_class = VerifyOtpFrom

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.htmx:
                return HttpResponseClientRedirect(reverse('home'))
            return redirect(reverse('home'))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {
            'form': self.form_class()
        }
        return render(request, template_name=self.template_name, context=context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.filter(phone_number=cd.get("phone_number")).first()
            otp = randint(10000, 99999)
            if user:
                user.first_name = cd.get("first_name")
                user.last_name = cd.get("last_name")
                user.set_password(cd.get("password"))
                user.otp = otp
                user.otp_expiry = timezone.now() + timedelta(seconds=settings.EXPIRE_OTP)
                user.save()
            else:
                instance = User()
                instance.first_name = cd.get("first_name")
                instance.last_name = cd.get("last_name")
                instance.phone_number = cd.get("phone_number")
                instance.otp = otp
                instance.set_password(cd.get("password"))
                instance.otp_expiry = timezone.now() + timedelta(seconds=settings.EXPIRE_OTP)
                instance.save()
            send_otp.apply_async((cd.get("phone_number"), otp), )
            context = {
                'form': self.confirm_form_class(initial={'phone_number': cd.get("phone_number")})
            }
            return render(request, template_name=self.confirm_template_name, context=context)
        return render(request, template_name=f"{self.template_name}#signup_form", context={'form': form})


class VerifySignup(View):
    form_class = VerifyOtpFrom
    template_name = "accounts/signup-otp-form.html"
    success_url = reverse_lazy('accounts:user-login-view')

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.get(phone_number=cd.get('phone_number'))
            user.is_active = True
            user.otp = None
            user.otp_expiry = None
            user.save()
            return HttpResponseClientRedirect(redirect_to=self.success_url)
        return render(request, template_name=f"{self.template_name}#verify_otp_form", context={'form': form})


class ProfileDetailView(LoginRequiredMixin, View):
    template_name = "accounts/profile-detail.html"
    form_class = UserProfileUpdateForm

    def get(self, request):
        context = {
            'form': self.form_class(initial={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
            })
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "اطلاعات پروفایل کاربری با موفقیت بروزرسانی شد.")
            return render(request, template_name="partials/alert.html")
        messages.error(request, form.errors)
        return render(request, template_name="partials/alert.html")


class ProfileOrdersView(LoginRequiredMixin, View):
    template_name = "accounts/profile-orders.html"

    def get(self, request):
        user_orders = Order.objects.prefetch_related("cart_items__product_variant__variant_image").filter(user=request.user)
        context = {
            'complete_orders': user_orders.filter(status__in=[OrderStatus.COMPLETED, OrderStatus.PAID]),
            'canceled_orders': user_orders.filter(status=OrderStatus.CANCELED)
        }
        return render(request, self.template_name, context)


def logout_view(request):
    logout(request)
    return redirect('home')

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR" data-theme="light" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{% static 'js/htmx.js' %}"></script>
    <script defer src="{% static 'js/alpine.js' %}"></script>
    {% block extra_head %}{% endblock extra_head %}
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% block content %}{% endblock %}
        {% block extra_script %}{% endblock %}
    </body>
</html>

accounts/templates/accounts/login-otp-form.html
{% load widget_tweaks %}
{% load partials %}

{% partialdef verify_otp_form inline %}
    <form x-data="otpForm()" hx-post="{% url 'accounts:user-login-verify-view' %}" hx-swap="outerHTML" hx-target="closest form">
        <div class="flex justify-between gap-2" x-ref="otpInputContainer" dir="ltr">
            <template x-for="(input, index) in length" :key="index">
                <input
                        type="tel"
                        maxlength="1"
                        class="otpInput w-14 h-14 text-center text-2xl font-bold input input-bordered"
                        @input="handleInput($event, index)"
                        @paste="handlePaste($event)"
                        @keydown.backspace="$event.target.value || handleBackspace($event, index)"
                />
            </template>
        </div>
        {% if form.otp.errors %}
            <div class="label">
                <span class="label-text-alt text-red-500">{{ form.otp.errors }}</span>
                <span class="label-text-alt"></span>
            </div>
        {% endif %}

        {% render_field form.phone_number type="hidden" %}
        {% render_field form.otp x-model="value" type="hidden" %}
        <button type="submit" class="btn btn-primary w-full my-3" :disabled="value.length !== length">تایید و ورود</button>
    </form>
{% endpartialdef %}
<script>
    function otpForm() {
        return {
            length: 5,
            value: "",

            get inputs() {
                return this.$refs.otpInputContainer.querySelectorAll('.otpInput');
            },

            handleInput(e, index) {
                const inputValues = [...this.inputs].map(input => input.value);
                this.value = inputValues.join('');
                if (e.target.value) {
                    const nextInput = this.inputs[index + 1];
                    if (nextInput) {
                        nextInput.focus();
                        nextInput.select();
                    }
                }
            },

            handlePaste(e) {
                const paste = e.clipboardData.getData('text').slice(0, this.length);
                paste.split('').forEach((char, i) => {
                    if (this.inputs[i]) {
                        this.inputs[i].value = char;
                    }
                });
                this.value = [...this.inputs].map(input => input.value).join('');
            },

            handleBackspace(e, index) {
                if (index > 0) {
                    this.inputs[index - 1].focus();
                    this.inputs[index - 1].select();
                }
            },
        };
    }
</script>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load partials %}

{% block title %}
    تهران بوتیک - ورود به فروشگاه
{% endblock %}

{% block content %}
    <main class="flex justify-center items-center gap-20 py-8 md:py-0 md:h-screen">
        <section class="flex flex-col items-end">
            <div class="w-[20rem]">
                <div class="flex flex-col items-center justify-center text-center">
                    <img src="{% static 'images/site/logo.png' %}"  width="200" alt="logo" class="mb-20 md:hidden">
                    {% include 'partials/alert.html' %}
                    <h1 class="hidden mb-24 text-xl font-bold md:block">به تهران بوتیک خوش آمدید</h1>
                    <h2 class="mb-8 font-bold">ورود</h2>
                </div>
                {% partialdef login_form inline %}
                    <form novalidate="novalidate" hx-post="{% url 'accounts:user-login-view' %}" hx-swap="outerHTML"
                          hx-target="closest form">
                        <label class="form-control w-full mb-2">
                            <span class="label-text mb-2">شماره تلفن</span>
                            {% render_field form.phone_number|add_error_class:"input-error" placeholder="شماره تلفن" class="input input-bordered w-full" %}
                            {% if form.phone_number.errors %}
                                <div class="label">
                                    <span class="label-text-alt text-xs text-error">{{ form.phone_number.errors }}</span>
                                </div>
                            {% endif %}
                        </label>
                        <p class="text-xs text-clip my-5">ورود و عضویت شما به منزله پذیرفتن قوانین و مقررات می باشد.</p>
                        <button type="submit" class="btn btn-primary w-full mb-3">ارسال کد تایید</button>
                    </form>
                {% endpartialdef %}
            </div>
            <a href="{% url 'accounts:user-signup-view' %}" class="link-primary w-full text-center mt-5">ثبت نام در سایت</a>
        </section>

        <section class="hidden md:block">
            <img src="{% static 'images/site/photo.png' %}" alt="login banner">
        </section>
    </main>
{% endblock %}

accounts/templates/accounts/profile-base.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="container py-4">
        <div id="messages" class="mb-4"></div>
        <h1 class="text-2xl font-bold my-5">پروفایل</h1>
        <section class="flex flex-col gap-5 lg:flex-row">
            <div class="flex flex-col h-fit w-full justify-center py-6 px-4 rounded-xl lg:px-9 lg:w-1/3 lg:border">
                <ul class="space-y-2">

                    <li>
                        <a href="{% url 'accounts:user-profile-orders' %}"
                           class="flex items-center gap-1 border-b pb-2 hover:border-primary hover:text-primary group {% if request.path == '/profile/orders-detail/' %}border-primary text-primary{% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                 class="fill-[#434343] group-hover:fill-primary">
                                <path
                                        d="M15 22.75H9c-5.43 0-7.75-2.32-7.75-7.75V9c0-5.43 2.32-7.75 7.75-7.75h6c5.43 0 7.75 2.32 7.75 7.75v6c0 5.43-2.32 7.75-7.75 7.75Zm-6-20C4.39 2.75 2.75 4.39 2.75 9v6c0 4.61 1.64 6.25 6.25 6.25h6c4.61 0 6.25-1.64 6.25-6.25V9c0-4.61-1.64-6.25-6.25-6.25H9Z"/>
                                <path
                                        d="M7.33 15.242c-.16 0-.32-.05-.46-.16a.749.749 0 0 1-.14-1.05l2.38-3.09c.29-.37.7-.61 1.17-.67.46-.06.93.07 1.3.36l1.83 1.44c.07.06.14.06.19.05.04 0 .11-.02.17-.1l2.31-2.98a.74.74 0 0 1 1.05-.13c.33.25.39.72.13 1.05l-2.31 2.98c-.29.37-.7.61-1.17.66-.47.06-.93-.07-1.3-.36l-1.83-1.44a.22.22 0 0 0-.19-.05c-.04 0-.11.02-.17.1l-2.38 3.09c-.13.2-.35.3-.58.3Z"/>
                            </svg>
                            <p>تاریخچه سفارشات</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user-profile-detail' %}"
                           class="flex items-center gap-1 border-b pb-2 hover:border-primary hover:text-primary group {% if request.path == '/profile/account-detail/' %}border-primary text-primary{% endif %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="fill-primary">
                                <path
                                        d="M12 12.75c-3.17 0-5.75-2.58-5.75-5.75S8.83 1.25 12 1.25 17.75 3.83 17.75 7s-2.58 5.75-5.75 5.75Zm0-10A4.26 4.26 0 0 0 7.75 7 4.26 4.26 0 0 0 12 11.25 4.26 4.26 0 0 0 16.25 7 4.26 4.26 0 0 0 12 2.75ZM20.59 22.75c-.41 0-.75-.34-.75-.75 0-3.45-3.52-6.25-7.84-6.25S4.16 18.55 4.16 22c0 .41-.34.75-.75.75s-.75-.34-.75-.75c0-4.27 4.19-7.75 9.34-7.75 5.15 0 9.34 3.48 9.34 7.75 0 .41-.34.75-.75.75Z"/>
                            </svg>
                            <p>اطلاعات حساب کاربری</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:user-logout-view' %}"
                           class="flex items-center gap-1 pb-2 hover:border-primary hover:text-primary group">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                 class="fill-[#434343] group-hover:fill-primary">
                                <path
                                        d="M17.44 15.367c-.19 0-.38-.07-.53-.22a.754.754 0 0 1 0-1.06l2.03-2.03-2.03-2.03a.754.754 0 0 1 0-1.06c.29-.29.77-.29 1.06 0l2.56 2.56c.29.29.29.77 0 1.06l-2.56 2.56c-.15.15-.34.22-.53.22Z"/>
                                <path
                                        d="M19.93 12.813H9.76c-.41 0-.75-.34-.75-.75s.34-.75.75-.75h10.17c.41 0 .75.34.75.75s-.34.75-.75.75Z"/>
                                <path
                                        d="M11.76 20.75c-5.15 0-8.75-3.6-8.75-8.75s3.6-8.75 8.75-8.75c.41 0 .75.34.75.75s-.34.75-.75.75c-4.27 0-7.25 2.98-7.25 7.25s2.98 7.25 7.25 7.25c.41 0 .75.34.75.75s-.34.75-.75.75Z"/>
                            </svg>
                            <p>خروج</p>
                        </a>
                    </li>
                </ul>
            </div>
            <hr class="h-px border lg:hidden">
            {% block profile-content %}{% endblock %}
        </section>
    </section>
{% endblock %}

accounts/templates/accounts/profile-detail.html
{% extends 'accounts/profile-base.html' %}
{% load static %}
{% load partials %}
{% load widget_tweaks %}

{% block title %}
    تهران بوتیک - پروفایل کاربری
{% endblock %}

{% block profile-content %}
    <div class="flex flex-col w-full justify-center py-6 px-4 rounded-xl lg:px-9 lg:w-2/3 lg:border">
        <strong class="text-2xl">اطلاعات حساب کاربری</strong>
                <div class="flex items-center w-full border-b mt-6">
                    <a href="#"
                       class="flex px-5 justify-center items-center gap-1 border-b border-primary text-primary pb-2 hover:border-base-200 hover:text-base-content">
                        اطلاعات کاربری
                    </a>
                </div>
                <form hx-post="{% url 'accounts:user-profile-detail' %}" hx-target="#messages" hx-swap="innerHTML" class="grid grid-cols-1 gap-6 pt-6 md:px-24 md:grid-cols-2">
                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">نام</span>
                        </div>
                        {% render_field form.first_name class="input input-bordered w-full" placeholder="نام" %}
                    </label>

                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">نام خانوادگی</span>
                        </div>
                        {% render_field form.last_name class="input input-bordered w-full" placeholder="نام خانوادگی" %}
                    </label>

                    <div class="form-control w-full">
                        <div class="label">
                            <span class="label-text">شماره تلفن</span>
                        </div>
                        <div class="input input-bordered w-full flex items-center bg-gray-200">{{ user.phone_number }}</div>
                    </div>

                    <button type="submit" class="btn btn-primary w-full md:w-fit md:px-16 md:ms-auto md:col-span-2">
                        ثبت اطلاعات
                    </button>
                </form>
            </div>
{% endblock %}