carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"
urlpatterns = [
    path('carts/promocode/', views.PromoCodeView.as_view(), name='promo-view'),
    path('carts/<int:pk>/', views.CartView.as_view(), name='cart-view'),
    path('carts/', views.CartView.as_view(), name='list-cart-view'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView
from azbankgateways.urls import az_bank_gateways_urls

admin.site.site_header = 'پنل مدیریت تهران بوتیک'
admin.site.index_title = 'پنل مدیریت فروشگاه'
admin.site.site_title = 'صفحه مدیریت تهران بوتیک'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('', include('accounts.urls', namespace="accounts")),
    path('', include('medias.urls', namespace="medias")),
    path('', include('products.urls', namespace="products")),
    path('', include('addresses.urls', namespace="addresses")),
    path('', include('carts.urls', namespace="carts")),
    path('', include('orders.urls', namespace="orders")),
    path("bankgateways/", az_bank_gateways_urls()),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"
urlpatterns = [
    path('store/', views.StoreView.as_view(), name='store-view'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('variant/<int:pk>', views.product_variants_choice, name='choice-variant-view'),
    path('search/', views.search_products, name='search-products'),
    # path('api/categories/', api_views.CategoryListView.as_view(), name='categories-list-api'),
    # path('api/categories/create/', api_views.CategoryCreateView.as_view(), name='categories-create-api'),
    # path('api/categories/update/<int:pk>/', api_views.CategoryUpdateView.as_view(), name='categories-update-api'),
    # path('api/categories/delete/<int:pk>/', api_views.CategoryDeleteView.as_view(), name='categories-delete-api'),
    # path('api/categories/<int:pk>/', api_views.CategoryRetrieveView.as_view(), name='categories-retrieve-api'),
    # path('api/products/', api_views.ProductListView.as_view(), name='products-list-api'),
    # path('api/products/create/', api_views.ProductCreateView.as_view(), name='products-create-api'),
    # path('api/products/update/<int:pk>/', api_views.ProductUpdateView.as_view(), name='products-update-api'),
    # path('api/products/delete/<int:pk>/', api_views.ProductDeleteView.as_view(), name='products-delete-api'),
    # path('api/products/<int:pk>/', api_views.ProductRetrieveView.as_view(), name='products-retrieve-api'),
    # path('api/products-variant/create/', api_views.ProductVariantCreateView.as_view(), name='products-variant-create-api'),
    # path('api/products-variant/delete/<int:pk>/', api_views.ProductVariantDeleteView.as_view(), name='products-variant-delete-api'),
    # path('api/products-variant/update/<int:pk>/', api_views.ProductVariantUpdateView.as_view(), name='products-variant-update-api'),
]

products/models.py
from django.db import models
from datetime import datetime
from medias.models import Image
from colorfield.fields import ColorField
from django.core.exceptions import ValidationError
from products import ProductType, StockStatus, DiscountType, VariableType
from core.models import AbstractNameDescriptionModel, AbstractSEOModel, AbstractBaseModel, AbstractPublishableModel
from statistics import mean
from django.utils.translation import gettext_lazy as _


class Category(AbstractNameDescriptionModel, AbstractSEOModel):
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='subcategories',
        verbose_name=_("Parent Category")
    )
    thumbnail = models.ForeignKey(
        Image,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_("Thumbnail")
    )

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Product(AbstractNameDescriptionModel, AbstractBaseModel, AbstractSEOModel, AbstractPublishableModel):
    summary = models.TextField(null=True, blank=True, verbose_name=_("Summary"))
    thumbnail = models.ForeignKey(
        Image,
        on_delete=models.PROTECT,
        verbose_name=_("Thumbnail")
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Category")
    )
    type = models.CharField(
        max_length=25,
        default=ProductType.SIMPLE_PRODUCT,
        choices=ProductType.choices,
        verbose_name=_("Product Type")
    )
    related_to = models.ManyToManyField(
        "self",
        blank=True,
        verbose_name=_("Related Products")
    )
    discount_type = models.CharField(
        max_length=25,
        choices=DiscountType.choices,
        blank=True,
        null=True,
        verbose_name=_("Discount Type")
    )
    discount_value = models.PositiveIntegerField(null=True, blank=True, verbose_name=_("Discount Value"))
    discount_start_date = models.DateField(null=True, blank=True, verbose_name=_("Discount Start Date"))
    discount_end_date = models.DateField(null=True, blank=True, verbose_name=_("Discount End Date"))

    class Meta:
        ordering = ('name',)
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    def is_discounted(self):
        if self.discount_value and self.discount_start_date <= datetime.now().date() <= self.discount_end_date and self.discount_type:
            return True
        return False

    def get_price_text(self):
        return f'{format(min([product.price for product in self.variants.all()]), ",")} تومان'

    def get_discounted_price(self):
        if not self.is_discounted():
            return self.get_price_text()
        original_price = min([product.price for product in self.variants.all()])
        discounted_price = 0

        if self.discount_type == DiscountType.PERCENTAGE:
            # Calculate percentage discount
            discount_amount = (original_price * self.discount_value) / 100
            discounted_price = original_price - discount_amount
        elif self.discount_type == DiscountType.CONSTANT:
            discounted_price = original_price - self.discount_value

        return f'{format(max(int(discounted_price), 0), ",")} تومان'

    def in_stock(self):
        return mean([product.stock for product in self.variants.all()]) > 0

    def clean(self):
        if self.discount_type:
            if not self.discount_value:
                raise ValidationError(_("Discount value is required."))
            if not self.discount_start_date or not self.discount_end_date:
                raise ValidationError(_("Discount start and end dates are required."))

    def __str__(self):
        return self.name


class ProductVariant(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='variants',
        verbose_name=_("Product")
    )
    variant_image = models.ForeignKey(
        Image,
        on_delete=models.PROTECT,
        verbose_name=_("Variant Image")
    )
    price = models.PositiveIntegerField(verbose_name=_("Price"))
    track_inventory = models.BooleanField(default=True, verbose_name=_("Track Inventory"))
    variables = models.ManyToManyField("Variable", blank=True, verbose_name=_("Variables"))

    stock = models.PositiveSmallIntegerField(default=0, verbose_name=_("Stock"))

    stock_status = models.CharField(
        default=StockStatus.IN_STOCK,
        choices=StockStatus.choices,
        max_length=15,
        verbose_name=_("Stock Status")
    )

    def decrease_stock(self, quantity):
        if self.stock < quantity:
            raise ValueError(_("Not enough stock available."))
        self.stock -= quantity
        self.save()

    def increase_stock(self, quantity):
        self.stock += quantity
        self.save()

    class Meta:
        ordering = ('price',)
        verbose_name = _('Product Variant')
        verbose_name_plural = _('Product Variants')

    def get_price_text(self):
        return f'{format(self.price, ",")} تومان'

    def __str__(self):
        return f"{self.product.name} | {', '.join(x.name for x in self.variables.all())}"


class Variable(models.Model):
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    color = ColorField(null=True, blank=True, verbose_name=_("Color"))
    variant_thumbnail = models.ForeignKey(
        Image,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_("Variant Thumbnail")
    )
    type = models.CharField(
        max_length=20,
        choices=VariableType.choices,
        default=VariableType.COLOR,
        verbose_name=_("Variable Type")
    )

    class Meta:
        verbose_name = _('Variable')
        verbose_name_plural = _('Variables')

    def __str__(self):
        return self.name

products/api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.generics import ListAPIView, CreateAPIView, UpdateAPIView, DestroyAPIView, RetrieveAPIView
from rest_framework.pagination import LimitOffsetPagination, PageNumberPagination
from products.api.serializers import CategorySerializer, ProductSerializer, ProductVariantSerializer
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework.permissions import IsAdminUser
from products.filters import ProductFilter
from products.models import Category, Product, ProductVariant
from rest_framework import filters


# Create your views here.
class CategoryListView(ListAPIView):
    queryset = Category.objects.filter(parent=None)
    serializer_class = CategorySerializer


class CategoryCreateView(CreateAPIView):
    queryset = Category.objects.filter(parent=None)
    serializer_class = CategorySerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)


class CategoryUpdateView(UpdateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (IsAdminUser,)
    authentication_classes = (JWTAuthentication,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class CategoryDeleteView(DestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (IsAdminUser,)
    authentication_classes = (JWTAuthentication,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class CategoryRetrieveView(RetrieveAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (IsAdminUser,)
    authentication_classes = (JWTAuthentication,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class ProductListView(ListAPIView):
    queryset = Product.objects.filter(published=True)
    serializer_class = ProductSerializer
    filter_backends = (filters.SearchFilter, DjangoFilterBackend, )
    filterset_class = ProductFilter
    search_fields = ['name', 'description']
    pagination_class = PageNumberPagination


class ProductCreateView(CreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)


class ProductUpdateView(UpdateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class ProductDeleteView(DestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class ProductRetrieveView(RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class ProductVariantCreateView(CreateAPIView):
    queryset = ProductVariant.objects.all()
    serializer_class = ProductVariantSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)


class ProductVariantDeleteView(DestroyAPIView):
    queryset = ProductVariant.objects.all()
    serializer_class = ProductVariantSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'


class ProductVariantUpdateView(UpdateAPIView):
    queryset = ProductVariant.objects.all()
    serializer_class = ProductVariantSerializer
    authentication_classes = (JWTAuthentication,)
    permission_classes = (IsAdminUser,)
    lookup_field = 'pk'
    lookup_url_kwarg = 'pk'

products/views.py
from django.conf import settings
from django.db.models import Max, Min
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import View, DetailView
from products import VariableTypeText
from products.filters import ProductFilter
from products.models import Product, ProductVariant
from django.core.paginator import Paginator
from itertools import groupby
from django.db.models import Prefetch


class StoreView(View):
    template_name = "products/store.html"

    def get(self, request):
        filter_set = ProductFilter(request.GET, queryset=Product.objects.all().order_by('-id'))
        paginator = Paginator(filter_set.qs, 12)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context = {
            **ProductVariant.objects.aggregate(Max('price'), Min('price')),
            'products': filter_set,
            'page_obj': page_obj
        }
        if request.htmx:
            return render(request, template_name=f'{self.template_name}#product_list', context=context)
        return render(request, template_name=self.template_name, context=context)


class ProductDetailView(DetailView):
    template_name = "products/single-product.html"
    model = Product
    context_object_name = "product"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_variants = ProductVariant.objects.filter(product=self.object).prefetch_related(
            Prefetch('variant_image'),
            Prefetch('variables')
        ).distinct().order_by('variables__name')
        variants_queryset = product_variants.values(
            "variables__id", "variables__name", "variables__type"
        )
        gallery_images = [
            settings.MEDIA_URL + x["variant_image__image"]
            for x in product_variants.values("variant_image__image").distinct()
        ]
        variants = [
            {'type': key, 'text': VariableTypeText[key], 'items': list(group)}
            for key, group in groupby(variants_queryset, key=lambda x: x["variables__type"])
        ]
        print(variants)

        context['variants'] = variants
        context['gallery_images'] = gallery_images

        return context


def product_variants_choice(request, pk):
    variant_ids = [int(value.split('|')[1]) for value in request.POST.values()]
    product = get_object_or_404(Product, pk=pk)

    variants = product.variants.all()
    for variant_id in variant_ids:
        variants = variants.filter(variables=variant_id)

    if not variants.exists():
        return HttpResponse("موجود نیست")

    if len(variants) == 1:
        variant = variants.first()

        context = {
            "variant_id": variant.id,
            "stock": range(1, variant.stock + 1),
            "price": variant.get_price_text(),
            "discounted_price": variant.product.get_discounted_price(),
            "is_discounted": variant.product.is_discounted()
        }
        return render(request, "products/add-to-cart.html", context=context)

    response = HttpResponse()
    response.headers["HX-Reswap"] = "none"
    return response


def search_products(request):
    query = request.GET.get('q', '').strip()
    if query:
        products = Product.objects.filter(name__icontains=query)[:4]
    else:
        products = Product.objects.none()

    return render(request, template_name="products/search-result.html", context={'products': products})

products/templates/products/add-to-cart.html
<div id="add-to-cart" class="mt-8">
    <div class="text-left mb-8">
        <p class="font-extrabold text-xl">
            {% if is_discounted %}
                <del class="text-red-500 me-2">{{ price }}</del>
                {{ discounted_price }}
                {% else %}
                {{ price }}
            {% endif %}
        </p>
    </div>

    <form class="flex justify-end gap-4 items-center" hx-post="{% url 'carts:cart-view' variant_id %}" hx-swap="innerHTML" hx-target="#messages">
        <select name="stock" class="select select-primary" {% if not stock %}disabled{% endif %}>
            <option disabled selected>تعداد</option>
            {% for number in stock %}
                <option>{{ number }}</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary" {% if not stock %}disabled{% endif %}>
            {% if not stock %}
                موجود نیست
                {% else %}
                افزودن به سبد خرید
            {% endif %}
        </button>
    </form>
</div>

products/templates/products/search-result.html
<div class="bg-white w-full rounded-b-2xl border-t p-4 flex flex-col gap-4">
    <h1 class="text-sm font-bold">نتایج جستجو</h1>
    {% if products %}
        {% for product in products %}
            <a href="{% url 'products:product-detail' product.id %}">
                <div class="border p-2 rounded-md grid grid-cols-12 gap-2">
                    <div class="col-span-2">
                        <img class="rounded" src="{{ product.thumbnail.image.url }}" alt="">
                    </div>
                    <div class="col-span-10">
                        <h1 class="font-bold">{{ product.name }}</h1>
                        <p class="text-sm mt-2">{{ product.get_price_text }}</p>
                    </div>
                </div>
            </a>
        {% endfor %}
        {% else %}
        <p class="text-center text-sm font-bold">نتیجه ای یافت نشد.</p>
    {% endif %}
</div>

products/templates/products/single-product.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load partials %}

{% block title %}
    تهران بوتیک - {{ product.name }}
{% endblock %}

{% block extra_head %}
    <meta name="format-detection" content="telephone=no">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="تهران بوتیک">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="تهران بوتیک">
    <meta property="og:title" content="{{ product.meta_title }}">
    <meta property="og:description" content="{{ product.meta_description }}">
    <meta property="og:image" content="{{ product.thumbnail.image.url }}">
    <meta property="og:image:alt" content="{{ product.meta_title }}">
    <meta name="description" content="{{ product.meta_description }}">
{% endblock %}

{% block content %}
    <div class="container grid grid-cols-12 lg:gap-8 p-2 lg:py-4">
        <div class="col-span-12 lg:col-span-4 space-y-2 block" dir="ltr">
            <div style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff"
                 class="swiper gallery rounded-lg relative">
                <div class="swiper-wrapper">
                    {% for image in gallery_images %}
                        <div class="swiper-slide">
                            <img class="rounded-lg" src="{{ image }}" alt=""/>
                        </div>
                    {% endfor %}
                </div>
                <div class="swiper-button-next"></div>
                <div class="swiper-button-prev"></div>
            </div>
            <div class="swiper thumbs">
                <div class="swiper-wrapper">
                    {% for image in gallery_images %}
                        <div class="swiper-slide opacity-50">
                            <img class="rounded-lg" src="{{ image }}" alt=""/>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-span-12 lg:col-span-8" x-data="onVariant()">
            <div id="messages" class="mt-4 lg:mt-0"></div>
            <div class="border-b py-4 mb-4">
                <h1 class="font-extrabold text-2xl text-primary">{{ product.name }}</h1>
            </div>

            <div class="leading-8 mb-4">
                {{ product.description|safe }}
            </div>
            <form class="flex gap-4" hx-post="{% url 'products:choice-variant-view' product.id %}" hx-trigger="change"
                  hx-target="#add-to-cart" hx-swap="outerHTML">
                {% for variant in variants %}
                    <select name="{{ variant.type }}" class="select select-primary"
                            @change="onChange($event.target.value, '{{ variant.type }}')">
                        <option disabled selected>{{ variant.text }}</option>
                        {% for item in variant.items %}
                            <option value="{{ forloop.counter0 }}|{{ item.variables__id }}">{{ item.variables__name }}</option>
                        {% endfor %}
                    </select>
                {% endfor %}
            </form>

            <div id="add-to-cart" class="mt-8">
                <div class="text-left mb-4">
                    <p class="font-extrabold text-xl">
                        {% if product.is_discounted %}
                            <del class="text-red-500 me-2">{{ product.get_price_text }}</del>
                            {{ product.get_discounted_price }}
                            {% else %}
                            {{ product.get_price_text }}
                        {% endif %}
                    </p>
                </div>

                <div class="flex justify-end gap-4">
                    <button class="btn btn-primary" disabled>
                        افزودن به سبد
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% if product.related_to.all %}
        <div class="container mt-8">
        <div class="flex items-center">
            <div class="flex gap-2 items-center text-nowrap me-10">
                <h3 class="font-extrabold text-lg">محصولات مرتبط</h3>
            </div>
            <hr class="w-full"/>
            <a class="btn btn-ghost btn-sm ms-4 text-primary" href="{% url 'products:store-view' %}">مشاهده بیشتر</a>
        </div>
        <div class="swiper product-carousel my-6">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    {% for foo in product.related_to.all %}
                        <a href="{% url 'products:product-detail' product.id %}">
                            <div class="col-span-3 border rounded-lg p-2">
                                <img class="object-cover max-h-72 w-full rounded-md"
                                     src="{{ product.thumbnail.image.url }}"
                                     alt="{{ product.thumbnail.alt_text }}">
                                <div class="mt-2">
                                    <h1 class="font-extrabold text-lg">{{ product.name }}</h1>
                                    <p class="text-sm font-bold mt-1">{{ product.summary }}</p>
                                    <p class="text-end font-extrabold">{{ product.get_price_text }}</p>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="swiper-button-next text-primary w-10 h-10 bg-white/80 rounded-full"></div>
            <div class="swiper-button-prev text-primary w-10 h-10 bg-white/80 rounded-full"></div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block extra_script %}
    <script>
        const gallery = new Swiper(".gallery", {
            spaceBetween: 10,
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            thumbs: {
                swiper: new Swiper(".thumbs", {
                    loop: false,
                    spaceBetween: 10,
                    watchSlidesProgress: true,
                    breakpoints: {
                        0: {
                            direction: 'horizontal',
                            slidesPerView: 3,
                        },
                        768: {
                            direction: 'horizontal',
                            slidesPerView: 4,
                        },
                        1024: {
                            direction: 'horizontal',
                            slidesPerView: 5,
                        },
                    }
                })
            },
        });
    </script>

    <script>
        function onVariant() {
            return {
                variants: {},
                onChange: (value, type) => {
                    if (type === 'LAYOUT' || type === 'COLOR') {
                        gallery.slideTo(value.split('|')[0]);
                        console.log(value.split('|')[0])
                    }
                    this.variants = {...this.variants, [type]: value.split('|')[1]}
                }
            }
        }
    </script>
    <script>
        new Swiper(".product-carousel", {
            slidesPerView: 4,
            spaceBetween: 24,
            grid: {},
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev",
            },
            breakpoints: {
                0: {
                    slidesPerView: 2,
                    spaceBetween: 24,
                },
                1024: {
                    slidesPerView: 5,
                    spaceBetween: 24,
                },
            },
        });
    </script>
{% endblock %}